# -*- coding: utf-8 -*-
"""movie_genre_clas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHruM42LxTLY-4m3lCE_2HbHIrc5oOAp
"""

import pandas as pd

train_df = pd.read_csv(
    "train_data.txt",
    sep=" ::: ",
    header=None,
    names=["ID", "TITLE", "GENRE", "DESCRIPTION"],
    engine="python"
)

train_df.head()

print("Rows and Columns:", train_df.shape)

train_df.isnull().sum()

train_df["GENRE"].value_counts().head(10)

train_df["DESCRIPTION"].str.len().describe()

train_df["desc_length"] = train_df["DESCRIPTION"].str.len()

train_df.head()

import matplotlib.pyplot as plt

genre_counts = train_df["GENRE"].value_counts().head(10)

plt.figure(figsize=(10,5))
genre_counts.plot(kind="bar")

plt.title("Top 10 Movie Genres")
plt.xlabel("Genre")
plt.ylabel("Count")

plt.show()

plt.figure(figsize=(10,5))

plt.hist(train_df["desc_length"], bins=50)

plt.title("Movie Description Length Distribution")
plt.xlabel("Length")
plt.ylabel("Frequency")

plt.show()

print("Number of unique genres:", train_df["GENRE"].nunique())

print(sorted(train_df["GENRE"].unique()))

X = train_df["DESCRIPTION"]

y = train_df["GENRE"]

print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

print(tfidf.get_feature_names_out()[:20])

print(tfidf.get_feature_names_out()[100:120])

from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train_tfidf, y_train)

y_pred_nb = nb_model.predict(X_test_tfidf)

from sklearn.metrics import accuracy_score

nb_accuracy = accuracy_score(y_test, y_pred_nb)

print("Naive Bayes Accuracy:", nb_accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_nb))

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred_nb,
    xticks_rotation=90
)

plt.show()

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=1000
)

lr_model.fit(X_train_tfidf, y_train)

y_pred_lr = lr_model.predict(X_test_tfidf)

lr_accuracy = accuracy_score(
    y_test,
    y_pred_lr
)

print("Logistic Regression Accuracy:", lr_accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_lr))

print("Naive Bayes Accuracy:", nb_accuracy)
print("Logistic Regression Accuracy:", lr_accuracy)

import matplotlib.pyplot as plt

models = ["Naive Bayes", "Logistic Regression"]
scores = [nb_accuracy, lr_accuracy]

plt.figure(figsize=(6,4))
plt.bar(models, scores)

plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")

plt.show()

print("Logistic Regression Accuracy:", lr_accuracy)

from sklearn.svm import LinearSVC

svm_model = LinearSVC()

svm_model.fit(X_train_tfidf, y_train)

y_pred_svm = svm_model.predict(X_test_tfidf)

svm_accuracy = accuracy_score(y_test, y_pred_svm)

print("SVM Accuracy:", svm_accuracy)

print("Naive Bayes:", nb_accuracy)
print("Logistic Regression:", lr_accuracy)
print("SVM:", svm_accuracy)

models = ["Naive Bayes", "Logistic Regression", "SVM"]
scores = [nb_accuracy, lr_accuracy, svm_accuracy]

plt.figure(figsize=(7,5))
plt.bar(models, scores)

plt.title("Model Comparison")
plt.ylabel("Accuracy")

plt.show()

def predict_genre(text):
    text_tfidf = tfidf.transform([text])
    prediction = lr_model.predict(text_tfidf)
    return prediction[0]

predict_genre(
    "A serial killer stalks victims in a haunted town."
)

import pickle

pickle.dump(lr_model, open("genre_model.pkl", "wb"))
pickle.dump(tfidf, open("tfidf_vectorizer.pkl", "wb"))

from sklearn.svm import LinearSVC

svm_model = LinearSVC()

svm_model.fit(X_train_tfidf, y_train)

y_pred_svm = svm_model.predict(X_test_tfidf)

from sklearn.metrics import accuracy_score

svm_accuracy = accuracy_score(y_test, y_pred_svm)

print("SVM Accuracy:", svm_accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_svm))

print("Naive Bayes:", nb_accuracy)
print("Logistic Regression:", lr_accuracy)
print("SVM:", svm_accuracy)

import matplotlib.pyplot as plt

models = ["Naive Bayes", "Logistic Regression", "SVM"]
scores = [nb_accuracy, lr_accuracy, svm_accuracy]

plt.figure(figsize=(8,5))
plt.bar(models, scores)

plt.title("Accuracy Comparison of Models")
plt.ylabel("Accuracy")

plt.show()

def predict_genre(description):
    description_tfidf = tfidf.transform([description])
    prediction = lr_model.predict(description_tfidf)
    return prediction[0]

predict_genre(
    "A haunted house is terrorized by evil spirits and mysterious murders."
)

predict_genre(
    "Two friends go on a hilarious road trip full of funny situations."
)

predict_genre(
    "A haunted house is terrorized by evil spirits and mysterious murders."
)

predict_genre(
    "A documentary exploring wildlife conservation and environmental challenges."
)

import pickle

pickle.dump(lr_model, open("movie_genre_model.pkl", "wb"))
pickle.dump(tfidf, open("tfidf_vectorizer.pkl", "wb"))

print("Model Saved Successfully!")

import pickle

pickle.dump(lr_model, open("movie_genre_model.pkl", "wb"))
pickle.dump(tfidf, open("tfidf_vectorizer.pkl", "wb"))

print("Model Saved Successfully!")