# -*- coding: utf-8 -*-
"""HANDWRITTEN TEXT  GENERATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpgrrVuZa6qQaFjieCssipOEsuhpwq5f
"""

!pip install datasets tensorflow

from datasets import load_dataset

dataset = load_dataset(
    "Skylion007/openwebtext",
    split="train",
    streaming=True
)

from datasets import load_dataset

dataset = load_dataset(
    "Skylion007/openwebtext",
    split="train",
    streaming=True
)

chars = sorted(list(set(text)))

char_to_idx = {
    c:i for i,c in enumerate(chars)
}

idx_to_char = {
    i:c for i,c in enumerate(chars)
}

vocab_size = len(chars)

print(vocab_size)

import numpy as np

seq_length = 100

X = []
y = []

for i in range(
    0,
    len(text)-seq_length,
    10
):

    seq = text[i:i+seq_length]
    target = text[i+seq_length]

    X.append(
        [char_to_idx[c] for c in seq]
    )

    y.append(
        char_to_idx[target]
    )

X = np.array(X)

y = np.array(y)

print(X.shape)
print(y.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

model = Sequential()

model.add(
    Embedding(
        vocab_size,
        64
    )
)

model.add(
    LSTM(
        128,
        return_sequences=True
    )
)

model.add(
    Dropout(0.2)
)

model.add(
    LSTM(128)
)

model.add(
    Dropout(0.2)
)

model.add(
    Dense(
        vocab_size,
        activation="softmax"
    )
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

history = model.fit(
    X,
    y,
    epochs=5,
    batch_size=128,
    validation_split=0.1
)

history2 = model.fit(
    X,
    y,
    epochs=5,
    batch_size=128,
    validation_split=0.1
)

model.save(
    "text_generator.keras"
)

def sample(preds, temperature=1.0):

    preds = np.asarray(preds).astype("float64")

    preds = np.log(preds + 1e-8) / temperature

    exp_preds = np.exp(preds)

    preds = exp_preds / np.sum(exp_preds)

    probas = np.random.multinomial(
        1,
        preds,
        1
    )

    return np.argmax(probas)

seed = "The future of technology and machine learning"
seed = seed[:100].ljust(100)

generated = seed

for i in range(500):

    x_pred = np.array(
        [[char_to_idx[c] for c in seed]]
    )

    preds = model.predict(
        x_pred,
        verbose=0
    )[0]

    next_index = sample(
        preds,
        temperature=0.7
    )

    next_char = idx_to_char[next_index]

    generated += next_char

    seed = seed[1:] + next_char

print(generated)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title('Training vs Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Training Loss','Validation Loss'])

plt.show()

plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('Training vs Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Training Accuracy','Validation Accuracy'])

plt.show()

with open("generated_text.txt","w") as f:
    f.write(generated)